# Builds the Gino into an executable for Windows & MacOS & Ubuntu
name: Build Pygame Executables

on:
  push:
    tags:
      - 'v*'  # Only build when you push a new version tag e.g v1.0

permissions:
  contents: write  # allow creating releases + uploading assets

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            dist/*.app
          tag_name: ${{ github.ref_name }}